### PR TITLE
switch license to apache

### PR DESCRIPTION
**Pull request by gregsheremeta**
switch license to apache

### CODE REVIEW

**Comment by gregsheremeta** [comment]
we don't have an approval process yet, so I'm going to merge this and we can make follow up PRs as needed

**Comment by accorvin** [comment]
@gregsheremeta any reason why you chose Apache specifically? We use GPLv3 elsewhere in the ODH.

**Comment by gregsheremeta** [comment]
The team talked about licenses the other day, and it wasn't clear to us which one is supposed to be used globally. Ironically, it's something we'll need an ADR for.

I'm surprised to hear GPLv3 is what we commonly use, for two reasons:

1 The subprojects in opendatahub-io seem mixed. I copied the LICENSE file from https://github.com/opendatahub-io/data-science-pipelines/blob/master/LICENSE -- although that is a fork, so maybe that one was a bad one to use as an example.

2 Projects that Red Hat productizes are usually Apache 2.0 -- oVirt, OpenStack, Kubernetes, Ansible ... all Apache 2.0.

All that said, this repo is text only, so Creative Commons is perhaps the most appropriate.

cc @LaVLaS

**Comment by gregsheremeta** [comment]
slack thread for further discussion: https://odh-io.slack.com/archives/C033X6XM448/p1676975429593999

**Pull request merged**
